#For the sake of similicity, tuning only 3 models

RandomForestClassifier:
  n_estimators: [80, 100, 120, 200]
  criterion: ['gini', 'entropy']
HistGradientBoostingClassifier:
  max_iter: [80, 100, 120, 200]
  learning_rate: [0.1, 0.001, 0.02]
KNeighborsClassifier:
  n_neighbors: [5, 7]
  weights: ['uniform', 'distance']

